FROM donaldrich/builder:latest  AS builder

ENV BOUNDRY_VERSION=0.1.0

RUN wget https://releases.hashicorp.com/boundary/${BOUNDRY_VERSION}/boundary${BOUNDRY_VERSION}_linux_amd64.zip
RUN unzip boundary${BOUNDRY_VERSION}_linux_amd64.zip

FROM alpine

COPY --from=builder  /boundary  /usr/local/bin/boundary

{{- template "validate" }}
