# FROM donaldrich/builder:latest AS vsh-builder
# RUN wget "https://github.com/fishi0x01/vsh/releases/download/v0.6.2/vsh_linux_amd64" -O /usr/local/bin/vsh
# RUN chmod +rx /usr/local/bin/vsh

# FROM alpine
# COPY --from=vsh-builder  /usr/local/bin/vsh  /usr/local/bin/vsh
# # COPY --from=donaldrich/hashicorp  /usr/local/bin/vault  /usr/local/bin/vault
# # validate
# COPY --from=donaldrich/function:task      /usr/local/bin/tusk /usr/local/bin/tusk
# COPY ./tusk.yml ./tusk.yml
# RUN tusk validate
# ENTRYPOINT [ "tusk" ]

{{- template "binary-upx" }}
