FROM projectatomic/dockerfile-lint:latest                     AS dockerfile_lint

# FROM node:10.3.0-alpine as base


# COPY    --from=dockerfilelint /dockerfilelint/ .
# RUN apk --no-cache add yarn

# COPY ./package.json /dockerfilelint/package.json
# COPY ./lib /dockerfilelint/lib
# COPY ./bin /dockerfilelint/bin

# WORKDIR /dockerfilelint
# RUN yarn --no-progress

# ENTRYPOINT ["/dockerfilelint/bin/dockerfilelint"]