FROM donaldrich/builder AS builder

RUN wget "https://www.naturaldocs.org/download/natural_docs/2.0.2/Natural_Docs_2.0.2.zip"

RUN unzip Natural_Docs_2.0.2.zip

FROM mono:latest

COPY --from=builder ["/Natural Docs","/Natural Docs"]
