FROM donaldrich/builder AS builder

RUN curl -L -o ./install-misspell.sh https://git.io/misspell
RUN sh ./install-misspell.sh

FROM alpine

COPY --from=builder /bin/misspell /usr/local/bin/misspell

{{- template "validate" }}
