FROM node:alpine

# RUN apt-get update && apt-get install -yqq python

# RUN apk add --no-cache python3 py3-pip ca-certificates git git-lfs openssh

# RUN pip3 install -U Commitizen

# RUN npm install -g commitizen

RUN apk --update --no-cache add git openssh
RUN npm install -g commitizen cz-conventional-changelog cz-customizable && \
  npm cache clean --force && \
  echo '{ "path": "cz-conventional-changelog" }' > ~/.czrc
