FROM donaldrich/builder:latest AS builder
RUN wget "https://github.com/kristofferahl/terraform-provider-healthchecksio/releases/download/v1.5.0/terraform-provider-healthchecksio_1.5.0_Linux_x86_64.tar.gz"
RUN tar xzf terraform-provider-healthchecksio_1.5.0_Linux_x86_64.tar.gz
# RUN chmod +rx {{ (datasource "data").image.tag }}
# RUN upx {{ (datasource "data").image.tag }}
# FROM alpine
# COPY --from=builder  {{ (datasource "data").image.tag }} /usr/local/bin/{{ (datasource "data").image.tag }}
