FROM donaldrich/builder as builder
RUN wget https://github.com/firecow/gitlab-ci-local/releases/latest/download/linux.gz
RUN gunzip linux.gz
RUN mv linux /usr/local/bin/gitlab-ci-local
RUN chmod +x /usr/local/bin/gitlab-ci-local
# FROM alpine

# COPY --from=builder   /usr/local/bin/gitlab-ci-local /usr/local/bin/gitlab-ci-local
{{- template "validate" }}
