FROM donaldrich/builder:latest          AS builder

RUN wget https://dev.yorhel.nl/download/ncdu-linux-x86_64-1.14.2.tar.gz

RUN tar xzf ncdu-linux-x86_64-1.14.2.tar.gz

RUN mv ncdu /usr/local/bin
RUN chmod a+x /usr/local/bin/ncdu

FROM alpine

COPY --from=builder   /usr/local/bin/ncdu  /usr/local/bin/ncdu

{{- template "validate" }}
