FROM node:alpine

RUN npm install markdown-magic --save-dev

RUN npm install -g markdown-pdf --ignore-scripts

RUN npm install markdownlint --save-dev

RUN npm install -g markdownlint-cli

RUN npm i markdown-spellcheck