FROM mvdan/shfmt as shfmt-builder

FROM donaldrich/builder:latest AS shellcheck-builder
RUN ginstall.sh shellcheck latest
RUN upx /usr/local/bin/shellcheck

FROM python:alpine

RUN pip install --no-cache-dir bashate

COPY --from=shellcheck-builder /usr/local/bin/shellcheck /usr/local/bin/shellcheck

COPY --from=shfmt-builder /bin/shfmt /usr/local/bin/shfmt

{{- template "validate" }}