
FROM donaldrich/builder AS builder
WORKDIR /data
RUN gget --verify-checksum=none github.com/YaleUniversity/packer-provisioner-goss packer-provisioner-goss-*-linux-amd64.tar.gz --stdout | tar -xzf- packer-provisioner-goss

# FROM donaldrich/builder:go AS packer-provisioner-comment-builder
# # RUN git clone https://github.com/SwampDragons/packer-provisioner-comment.git
# # WORKDIR /packer-provisioner-comment
# # RUN go mod init main
# # RUN go build
# # RUN mv main packer-provisioner-comment
# RUN GO111MODULE=on go get -v github.com/SwampDragons/packer-provisioner-comment

FROM alpine

COPY --from=builder /data/* /usr/local/bin/
COPY --from=hashicorp/packer /bin/packer /usr/local/bin/packer

COPY --from=mkaczanowski/packer-builder-arm:latest /bin/packer-builder-arm /usr/local/bin/packer-builder-arm
COPY --from=quay.io/solo-io/packer-builder-arm-image:v0.1.6 /bin/packer-builder-arm-image usr/local/bin/packer-builder-arm-image

# COPY --from=packer-builder  /usr/local/bin/packer  /usr/local/bin/packer
# COPY --from=packer-builder-arm-builder /usr/local/bin/packer-builder-arm  /usr/local/bin/packer-builder-arm
# COPY --from=packer-builder-arm-image-builder /usr/local/bin/packer-builder-arm-image  /usr/local/bin/packer-builder-arm-image
# COPY --from=packer-provisioner-goss-builder  /usr/local/bin/packer-provisioner-goss  /usr/local/bin/packer-provisioner-goss

{{- template "validate" }}
