FROM donaldrich/builder:latest AS abs-builder
ADD https://github.com/abs-lang/abs/releases/download/2.3.1/abs-linux-amd64 /usr/local/bin/abs
RUN chmod +rx /usr/local/bin/abs
RUN upx /usr/local/bin/abs
