FROM donaldrich/builder:latest AS builder

WORKDIR /data

RUN gget --stdout github.com/junegunn/fzf fzf-*-linux_amd64.tar.gz | tar -xzf- fzf
RUN gget github.com/restic/restic restic_*_linux_amd64.bz2
RUN gget --stdout github.com/upx/upx upx-*-amd64_linux.tar.xz | tar -xJf-
RUN gget --executable github.com/dpb587/gget gget='gget-*-linux-amd64'
RUN gget --executable github.com/mholt/archiver arc='arc_*_linux_amd64'
RUN gget --executable github.com/gruntwork-io/fetch fetch='fetch_linux_amd64'
RUN gget --stdout github.com/jesseduffield/horcrux horcrux_*_Linux_x86_64.tar.gz | tar -xzf- horcrux
RUN gget --executable github.com/whalehub/ginstall.sh ginstall.sh='ginstall.sh'
RUN gget --executable github.com/coord-e/magicpak  magicpak='magicpak-x86_64-unknown-linux-musl'
RUN gget --executable github.com/megastep/makeself  makeself='makeself-*.run'

FROM ubuntu

RUN apt-get update && apt-get install --no-install-recommends -y curl ncdu tar unzip tree duc ca-certificates \
&& rm -rf /tmp/* /usr/share/doc/* \
  /usr/share/locale/* /usr/share/man/* \
  /var/cache/debconf/* /var/cache/apt/* \
  /var/tmp/* /var/log/* /var/lib/apt/lists/* \
  apt-get autoclean && \
  apt-get autoremove --purge && \
  apt-get clean

COPY --from=builder /data/* /usr/local/bin/
# RUN ginstall.sh --first-run && ginstall.sh --self-update

COPY ./extract.sh /usr/local/bin/extract
# validate
{{- template "validate" }}
