FROM donaldrich/builder:latest AS fzf-builder
RUN ginstall.sh fzf latest
RUN upx /usr/local/bin/fzf

FROM donaldrich/builder:latest AS restic-builder
RUN ginstall.sh restic latest
RUN upx /usr/local/bin/restic

FROM donaldrich/builder:latest AS upx-builder
RUN ginstall.sh upx latest

FROM donaldrich/builder:latest AS ncdu-builder
RUN wget -O archive.tar.gz "https://dev.yorhel.nl/download/ncdu-linux-x86_64-1.14.2.tar.gz"
RUN tar xzf archive.tar.gz
RUN upx ncdu
RUN mv ncdu /usr/local/bin
RUN chmod a+x /usr/local/bin/ncdu

FROM donaldrich/builder:latest AS fetch-builder
RUN wget "https://github.com/gruntwork-io/fetch/releases/download/v0.3.10/fetch_linux_amd64" -O /usr/local/bin/fetch
RUN chmod +rx /usr/local/bin/fetch
RUN upx /usr/local/bin/fetch

FROM donaldrich/builder:latest AS horcrux-builder
RUN wget -O archive.tar.gz "https://github.com/jesseduffield/horcrux/releases/download/v0.2/horcrux_0.2_Linux_x86_64.tar.gz"
RUN tar xzf archive.tar.gz
RUN upx horcrux
RUN mv horcrux /usr/local/bin
RUN chmod a+x /usr/local/bin/horcrux

FROM donaldrich/builder:latest AS ginstall-builder
ENV VERSION 3.4.0
RUN wget "https://github.com/whalehub/ginstall.sh/releases/download/v$VERSION/ginstall.sh" -O /usr/local/bin/ginstall.sh
RUN chmod +rx /usr/local/bin/ginstall.sh
RUN upx /usr/local/bin/ginstall.sh

FROM ubuntu

RUN apt-get update && apt install -y curl tar unzip

COPY --from=ginstall-builder /usr/local/bin/ginstall.sh /usr/local/bin/ginstall.sh

RUN ginstall.sh --first-run && ginstall.sh --self-update

COPY --from=horcrux-builder /usr/local/bin/horcrux /usr/local/bin/horcrux

COPY --from=fetch-builder  /usr/local/bin/fetch  /usr/local/bin/fetch

COPY --from=ncdu-builder /usr/local/bin/ncdu /usr/local/bin/ncdu

COPY --from=upx-builder /usr/local/bin/upx /usr/local/bin/upx

COPY --from=restic-builder /usr/local/bin/restic /usr/local/bin/restic

COPY --from=fzf-builder /usr/local/bin/fzf /usr/local/bin/fzf

{{- template "validate" }}
