# FROM quay.io/ukhomeofficedigital/vault-sidekick AS builder

# FROM alpine

# COPY --from=builder /vault-sidekick /usr/local/bin/vault-sidekick

# ENTRYPOINT ["vault-sidekick"]

# CMD ["-help"]

{{- template "docker-transfer-upx" }}
{{- template "validate" }}
