FROM replicated/dockerfilelint:latest                     AS dockerfilelint

# FROM    donaldrich/builder:latest                  AS builder
# COPY    --from=dockerfilelint /dockerfilelint/bin/dockerfilelint /usr/local/bin/dockerfilelint
# # RUN     upx /usr/local/bin/dockerfilelint
# RUN chmod +rx /usr/local/bin/dockerfilelint
# RUN /usr/local/bin/dockerfilelint -h

# FROM scratch

# COPY --from=builder  /usr/local/bin/dockerfilelint  /usr/local/bin/dockerfilelint