FROM donaldrich/builder:go AS converge-builder

RUN go get github.com/asteris-llc/converge

FROM alpine

COPY --from=converge-builder /root/go/bin/converge /usr/local/bin/converge

{{- template "validate" }}