FROM donaldrich/builder AS goscan-builder

RUN wget https://github.com/marco-lancini/goscan/releases/download/v2.4/goscan_2.4_linux_amd64.zip
RUN unzip goscan_2.4_linux_amd64.zip
RUN mv goscan /usr/local/bin