FROM node:alpine

RUN npm install -g \
npm@7.3.0 \
markdown-pdf \
markdownlint \
markdownlint-cli \
remark-cli \
remark-preset-lint-recommended \
markdown-link-check \
markdown-spellcheck \
textlint

# RUN npm install markdown-magic

# RUN npm install -g markdown-pdf --ignore-scripts

# RUN npm install markdownlint --save-dev

# RUN npm install -g markdownlint-cli

# RUN npm install --save remark-cli remark-preset-lint-recommended

# RUN npm install -g markdown-link-check

# RUN npm install textlint --global

# COPY ./package.json ./
